name: Version Update

on:
  workflow_dispatch:
  workflow_call:

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Check CHANGELOG.md exists
        id: check_changelog
        run: |
          if [ ! -f CHANGELOG.md ]; then
            echo "# Changelog" > CHANGELOG.md
            echo "Creating new CHANGELOG.md file"
          fi

      - name: Get current version
        id: current_version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "current=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Update patch version
        id: new_version
        run: |
          NEW_VERSION=$(node -p "const [major, minor, patch] = '$(cat package.json | jq -r .version)'.split('.'); `${major}.${minor}.${Number(patch) + 1}`")
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          npm version patch --no-git-tag-version

      - name: Update CHANGELOG.md
        run: |
          DATE=$(date +"%Y-%m-%d")
          if [ ! -s CHANGELOG.md ]; then
            echo "# Changelog" > CHANGELOG.md
          fi
          echo "
          ## [${NEW_VERSION}] - ${DATE}
          - Patch update from ${CURRENT_VERSION} to ${NEW_VERSION}

          $(cat CHANGELOG.md | sed '1,1d')" > CHANGELOG.md
        env:
          CURRENT_VERSION: ${{ steps.current_version.outputs.current }}
          NEW_VERSION: ${{ steps.new_version.outputs.version }}

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Check if we're on a PR
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            # Get the PR branch name
            branch_name="${{ github.head_ref }}"
            git checkout -b $branch_name
          else
            git checkout -b "version-update/${{ steps.new_version.outputs.version }}"
          fi
          
          git add package.json CHANGELOG.md
          git commit -m "chore: bump version to ${{ steps.new_version.outputs.version }}"
          
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            git push origin HEAD:${{ github.head_ref }} --force
          else
            git push origin "version-update/${{ steps.new_version.outputs.version }}" --force
            
            # Create PR if not already exists
            gh pr create --title "chore: bump version to ${{ steps.new_version.outputs.version }}" \
                        --body "Automated version bump to ${{ steps.new_version.outputs.version }}" \
                        --base main \
                        --head "version-update/${{ steps.new_version.outputs.version }}" \
                        --label "version-bump" || true
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      new_version: ${{ steps.new_version.outputs.version }}

  trigger-build:
    needs: update-version
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.name,
              workflow_id: 'build.yml',
              ref: 'version-update/${{ needs.update-version.outputs.new_version }}'
            });
